# Generated by Django 3.2.8 on 2021-10-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_studentclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name_plural': 'Student Classes'},
        ),
        migrations.AddField(
            model_name='studentclass',
            name='enrolled_student_names',
            field=models.JSONField(default=[]),
        ),
    ]
