# Generated by Django 3.2.8 on 2021-10-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20211023_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='enrolled_student_names',
            new_name='enrolled_users',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='enrolled_users_count',
            field=models.IntegerField(default=0),
        ),
    ]
