# Generated by Django 3.2.7 on 2021-10-24 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0005_auto_20211023_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='enrolled_users',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
