# Generated by Django 3.2.7 on 2021-10-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20211028_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='users',
            field=models.ManyToManyField(to='scheduler.Profile'),
        ),
    ]
