# Generated by Django 3.2.7 on 2021-10-28 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0009_alter_studentclass_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='tudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=200)),
                ('instructor', models.CharField(default='', max_length=200)),
                ('enrolled_users_count', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Classes',
            },
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
