# Generated by Django 3.2.7 on 2021-10-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20211028_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=200)),
                ('instructor', models.CharField(default='', max_length=200)),
                ('enrolled_users_count', models.IntegerField(default=0)),
                ('userToClass', models.ManyToManyField(to='scheduler.Profile')),
            ],
            options={
                'verbose_name_plural': 'Student Classes',
            },
        ),
        migrations.DeleteModel(
            name='tudentClass',
        ),
    ]
