# Generated by Django 3.2.7 on 2021-10-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20211028_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='userToClass',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='users',
        ),
    ]
