# Generated by Django 3.2.7 on 2021-10-28 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0013_auto_20211028_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
