# Generated by Django 3.2.7 on 2021-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_studentclass_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='users',
            field=models.ManyToManyField(to='scheduler.Profile'),
        ),
    ]
