# Generated by Django 3.2.8 on 2021-10-30 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20211030_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
