# Generated by Django 3.2.8 on 2021-10-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20211030_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='end_time',
            field=models.TimeField(help_text='Please use the following format:  HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='start_time',
            field=models.TimeField(help_text='Please use the following format:  HH:MM', null=True),
        ),
    ]
