# Generated by Django 3.2.7 on 2021-10-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_alter_studentclass_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='days',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
