# Generated by Django 3.2.7 on 2021-10-31 23:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_auto_20211031_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=56),
        ),
    ]
