# Generated by Django 3.2.8 on 2021-11-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_rename_days_studentclass_days_of_the_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FileField(upload_to='')),
                ('title', models.CharField(default='', max_length=200)),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentclass',
            name='notes',
            field=models.ManyToManyField(to='scheduler.NoteFile'),
        ),
    ]
