# Generated by Django 3.2.8 on 2021-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_auto_20211106_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='user',
            field=models.ManyToManyField(to='scheduler.Profile'),
        ),
    ]
