# Generated by Django 3.2.8 on 2021-11-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_rename_note_notefile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notefile',
            old_name='file',
            new_name='note',
        ),
    ]
