# Generated by Django 3.2.9 on 2021-11-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_rename_file_notefile_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('users', models.ManyToManyField(to='scheduler.Profile')),
            ],
        ),
    ]
