# Generated by Django 3.2.9 on 2021-11-07 03:40
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_event'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='todolistitem',
        #    name='users',
        #),
        #migrations.AddField(
        #    model_name='todolistitem',
        #    name='users',
        #    field=models.ManyToManyField(to='scheduler.Profile')
        #    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.profile'),
        #),
    ]
