# Generated by Django 3.2.9 on 2021-11-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_auto_20211106_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='todolistitem',
            name='users',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='users',
            field=models.ManyToManyField(to='scheduler.Profile'),
        ),
    ]
