# Generated by Django 3.2.9 on 2021-11-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0031_auto_20211110_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to='scheduler.Profile'),
        ),
    ]
