# Generated by Django 3.2.9 on 2021-12-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0032_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
